version: '2.1'

services:
  startup_server:
    build: ./
    volumes:
      - ./:/usr/src/app:rw
  peer1:
    build: ./
    volumes:
      - ./:/usr/src/app:rw
  peer2:
    build: ./
    volumes:
      - ./:/usr/src/app:rw
  peer3:
    build: ./
    volumes:
      - ./:/usr/src/app:rw
