version: '2.1'

services:
  startup_server:
    build: ./
    volumes:
      - ./:/usr/src/app:ro
      - ./logs/:/usr/src/app/logs:rw
    entrypoint:
      - python3
      - ./main.py
      - startup
    environment:
      LOG_FILE: ./logs/start_server.log
  peer1:
    build: ./
    volumes:
      - ./:/usr/src/app:ro
      - ./logs/:/usr/src/app/logs:rw
    environment:
      LOG_FILE: ./logs/peer1.log
  peer2:
    build: ./
    volumes:
      - ./:/usr/src/app:ro
      - ./logs/:/usr/src/app/logs:rw
    environment:
      LOG_FILE: ./logs/peer2.log
  peer3:
    build: ./
    volumes:
      - ./:/usr/src/app:ro
      - ./logs/:/usr/src/app/logs:rw
    environment:
      LOG_FILE: ./logs/peer3.log
